# Generated by Django 3.0.1 on 2020-01-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200108_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
