# Generated by Django 3.0.1 on 2020-01-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_tag_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
        migrations.CreateModel(
            name='Append',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='append', to='stories.Recipe', verbose_name='Recipe')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='append', to='stories.Story', verbose_name='Story')),
            ],
            options={
                'verbose_name': 'Append',
                'verbose_name_plural': 'Appends',
                'db_table': 'Append',
            },
        ),
    ]
