# Generated by Django 3.0.1 on 2020-01-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20200124_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='append',
            name='recipe',
        ),
        migrations.AddField(
            model_name='story',
            name='description',
            field=models.TextField(default='asdasdasd', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(default='Ner ttitkele', max_length=50, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='append',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='append',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='append',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
