# Generated by Django 3.0.1 on 2020-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_auto_20200128_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(default='', upload_to='media/cover', verbose_name='Cover photo'),
            preserve_default=False,
        ),
    ]
